### ISSUE TITLE
About optimizers

### ISSUE THREAD

**Issue by raul-tez** [shahriar-rahman/Prediction-of-Solar-Radiation#4]
Hi, can a Gradient Descent optimizer be used without affecting the predictability of the model? Thank you!

**Comment by shahriar-rahman** [comment]
Hey, Gradient Descent Optimizer provided decent results. However, for this experiment. Adam worked the best since it is an amalgamation of both the Gradient Descent with momentum and RMSProp. So basically, it’s the best of two worlds.
